### ISSUE TITLE
This error occurred when the flow tried to look up records: Disjunctions not supported.

### ISSUE THREAD

**Issue by cchrisv** [douglascayers/sfdx-mass-action-scheduler#45] opened 2018-09-22 16:10 UTC
It seems mass action scheduler has issues processing custom metadata. This works without an issue when I run it through the debugger but kicks the error below when I attempt to run it through mass-action-scheduler. I'm assuming its related to the batching because custom metadata has limited support for SOQL query type.

FAST LOOKUP: Fast_lookup_Queue_API
Find all Actions_Search_Match__mdt records where:
SubType__c Equals {!Other} (None)
SubType_Detail__c Equals {!Affiliation} (1)
Type__c Equals {!Department} (2)
Assign those records to {!QueueData}.
Save these field values in the variable: Queue_API__c
Result
Failed to find records.
Error Occurred: This error occurred when the flow tried to look up records: Disjunctions not supported. You can look up ExceptionCode values in the SOAP API Developer Guide.

**Comment by douglascayers** [comment] 2018-11-17 05:37
Hi @cchrisv,

That is interesting. I'd never seen the error *Disjunctions not supported* and in a quick Google search only came across this post https://salesforce.stackexchange.com/questions/169815/disjunctions-not-supported.

I wonder if the issue is the very first limitation mentioned in [Custom Metadata Types Limitations](https://help.salesforce.com/articleView?id=custommetadatatypes_limitations.htm&type=0) around Apex code updating records and code being in a managed package. How I'm interpreting that article is that the managed Apex code of Mass Action Scheduler would not be able to update the CMDT records in your org (the subscriber org) because the Apex and the CMDT are not in the same namespace.

**Comment by douglascayers** [comment] 2018-12-31 02:59
I'm closing this for now as I believe the issue is Apex limitation of updating custom metadata types in different namespaces as mentioned in earlier comment. Sorry

**Closed by douglascayers** 2018-12-31 02:59 UTC
Labels: question
