### ISSUE TITLE
Unable to run Flows that make Callouts

### ISSUE THREAD

**Issue by bruceleestewart** [douglascayers/sfdx-mass-action-scheduler#22] opened 2018-02-16 04:56 UTC
Receiving error "System.CalloutException: Callout loop not allowed" - even with batch size of 1, when attempting to use invocable flow methods from External Services / BETA Integrations in SF.  (Swagger Schema).  Our Flow contains methods that when run in screen flow or autolaunch flow, can call out to web service endpoints.

Architecture of Mass Action Scheduler *may* be preventing callouts in Flow.  Doug- can you verify?
Error
https://help.salesforce.com/articleView?id=000232321&type=1
Citation
https://help.salesforce.com/articleView?id=000232321&type=1

**Comment by DouglasCAyers** [comment] 2018-02-16 06:44
This may be a limitation in how Mass Action Scheduler works. The app uses the Salesforce REST API to invoke the chosen action (flow). So what I understand in that help article is that the callout from the flow itself is being blocked because apex code already made a callout. 

For grins to see if this workaround helps, could you try adding a flow Wait element before the flow calls the external service? That might cause a new apex transaction to occur and so reset the http callout limit. I’m not saying that is or isn’t a good thing to do, but something to try.

**Comment by DouglasCAyers** [comment] 2018-03-30 22:04
@bruceleestewart I'm going to escalate to the Apex and Flow teams to see if this is "by design" or "fixable".

**Comment by bruceleestewart** [comment] 2018-05-12 02:56
Doug:

I haven’t been on Github in a while to reply. Thank you for looking into this, and confirming your original gut-check.  I see tremendous potential in external services / callouts in general. I get that our system has limitations. 

Frankly Mass Action Scheduler is so useful to me every day, it was a little shocking to find something it couldn’t do. Thank you for crafting this tool, and for your thorough reply!  

Bruce

**Comment by douglascayers** [comment] 2019-01-06 01:41
Thanks for the kind feedback @bruceleestewart.

Since this is blocked by Salesforce's architecture, and I'm not sure if that limitation will change, I'm going to close this issue for now. I've added to the [FAQ](https://github.com/douglascayers/sfdx-mass-action-scheduler/wiki/Frequently-Asked-Questions#error-systemcalloutexception-callout-loop-not-allowed).

Thanks

**Closed by douglascayers** 2019-01-06 01:41 UTC
Labels: Type: Salesforce Known Issue
