### ISSUE TITLE
Error invoking Process Builder

### ISSUE THREAD

**Issue by longaaronsilver** [douglascayers/sfdx-mass-action-scheduler#40] opened 2018-08-11 12:24 UTC
Hi Douglas, love your work.

I'm trying to use this tool to fire a process in process builder every day on all records that match the criteria, rather than just when a record updates.

I though I'd set it all up correctly, but when I run the configuration, it spits back loads of these errors: 

Error: System.HttpResponse[Status=Bad Request, StatusCode=400]
[{"actionName":"Update_Action_from_Scheduler","errors":[{"statusCode":"UNKNOWN_EXCEPTION","message":"An error occurred when executing a flow interview.","fields":[]}],"isSuccess":false,"outputValues":null},

This error goes on for ages, probably about 200 records I suppose.

I'm not a dev, I have no idea what I'm looking at - are you able to assist at all?

Thanks.

**Comment by longaaronsilver** [comment] 2018-08-15 04:45
Thanks Doug,

Would it be possible for me to walk through with you what I've done to make sure it's not just a setup error?

Kind regards,


Aaron Steele

________________________________

**Comment by douglascayers** [comment] 2018-08-30 00:48
Hi @longaaronsilver,

Some folks report that when they get the vague error message like you did, `An error occurred when executing a flow interview.`, that the cause usually is like a validation rule or other triggers/automation in the org that are being kicked off and themselves are failing or causing the action to not complete correctly.

To troubleshoot, you may want to try out a super simple process or flow on a custom object that is guaranteed to not have any validation rules or triggers or workflows rules, etc on them to get in the way. If you can build a simple successful scenario, then that may help with troubleshooting when it doesn't work with other objects/actions.

**Comment by MikeVenman** [comment] 2018-10-01 20:52
Hi there.  I'm having the same issue when trying to use this tool.  I did exactly what you suggested to do - re custom object, super simple process, and it worked perfectly.

For the life of me, I can't find any validation rule, workflow, process builder, etc.. that causes an error.  I was also changing the lead owner, and adjusted it to edit a custom field on the lead, but got the same result.

It ended up being that the batch size was too big at the basic 200... once I closed the batch size down to 10, it worked without a problem...  So batch size is another option.

Thanks for the great tool @douglascayers.

**Comment by douglascayers** [comment] 2018-11-18 03:59
You're very welcome @MikeVenman, thanks for the tips on reducing **batch size**.

**Comment by douglascayers** [comment] 2019-01-06 03:03
I'm closing this issue, if you still encounter the problem with the new version feel free to comment back and we can continue to discuss.

Reminder, traditionally, those process builder/flow error emails are sent to the user who last modified the process or flow, but in Setup you can [change who receives the notifications](https://help.salesforce.com/articleView?id=vpm_admin_error_email.htm&type=5) if you didn't receive one (also check spam folder). And if you're doing this in a sandbox, make sure [email deliverability](https://help.salesforce.com/articleView?id=emailadmin_send_through_salesforce_configure_deliverability.htm&type=5) is set to All email to make sure you get the error emails with the specific details in them, too.

**Closed by douglascayers** 2019-01-06 03:03 UTC
Labels: action: process builder & flows, discussion 💬
